version: '3.4'
services:
    web:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      ports:
        - '3000:82'
      volumes:
        - '.:/app'
        - '/app/node_modules'
      restart: always
      mem_limit: 512m