version: '3.8'
name: skillup
services:
  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          cpus: '0.3'
          memory: 32M
