version: '3.8'
name: skillup
services:
  frontend:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.3'
          memory: 32M
    stdin_open: true