version: '3.8'
name: skillup
services:
  frontend:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
