FROM node:16 as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:16-alpine3.18
RUN npm install -g serve
WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install --only=production
COPY --from=builder /usr/src/app/build ./build
# COPY public /usr/src/app/public

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]